name: Build Web Application
on: 
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Clean old build
        run: rm -rf dist
      - name: Build Web
        run: pnpm build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=esume-tailor
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
